added frogbot install
eyalk007/jfrog-github-app pull request #1
Opened 2024-09-29 14:12 UTC by eyalk007

2024-10-09 13:31 UTC, attiasas requested changes
Nice!, please take a look at my comments.
In addition:
1. Add tests
2. Update README.md with details

2024-10-09 13:31 UTC, attiasas commented on src/utils/consts.ts
> +    prTitle: "Added Frogbot configurations",
```suggestion
    prTitle: "Set Up Frogbot Capabilities for Security and Compliance",
```

2024-10-09 13:31 UTC, attiasas commented on message.md
> +> Happy coding! 🎉
```suggestion
# 👋 Hi there!

Welcome to the **JFrog App** 🐸.

This Pull Request introduces the integration of **Frogbot** into this repository, adding two important actions:

1. **PR Security Review**: Frogbot will automatically scan every pull request for security vulnerabilities and license compliance issues, helping ensure that insecure code doesn't get merged.
2. **Branch Scanning on Push/Schedule**: In addition to PR scanning, Frogbot will also regularly scan branches on every push and on a defined schedule to maintain ongoing security.

Before merging this PR, please review and validate that the changes are appropriate for your project’s workflow and that the Frogbot configuration aligns with your security needs.

For more details on Frogbot's capabilities and configuration options, visit the official [Frogbot documentation](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot).

Happy coding! 🎉
```

2024-10-09 13:31 UTC, attiasas commented on src/app.ts
> +  if (payload.action === "added") {
only on added repos? what about old one? make sure not to add if exists already

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +        //TODO: add reviewers funcionality
`TODO` comment here, making sure you are aware of it. I can only see creating env, not setting reviewers

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +            console.error('Error adding maintainers to environment:', error);
error log not matching the method, we are creating env here not adding maintainers

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +            ]);
```suggestion
            await Promise.all([
                this.octokit.rest.repos.createOrUpdateFileContents({
                    owner,
                    repo,
                    path: '.github/workflows/frogbot-scan-repository.yml',
                    message: `Added frogbot-scan-repository.yml on ${PULL_REQUEST_DATA.branchName}`,
                    content: Buffer.from(this.scanRepositoryWorkflow(defaultBranch)).toString('base64'),
                    branch: PULL_REQUEST_DATA.branchName,
                }),
                this.octokit.rest.repos.createOrUpdateFileContents({
                    owner,
                    repo,
                    path: '.github/workflows/frogbot-scan-pull-request.yml',
                    message: `Added frogbot-scan-pull-request.yml on ${PULL_REQUEST_DATA.branchName}`,
                    content: Buffer.from(this.pullRequestWorkflow()).toString('base64'),
                    branch: PULL_REQUEST_DATA.branchName,
                }),
            ]);
```
vars with values from methods. only used once

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +jobs:
```suggestion
        return `Name: Frogbot pull request scan"
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
jobs:
```
missing some configs to the action

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +      - uses: jfrog/frogbot@v2.21.13
```suggestion
      - uses: jfrog/frogbot@v2
```
Use latest version, instead of the constant

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +      - uses: jfrog/frogbot@v2.21.13
```suggestion
      - uses: jfrog/frogbot@v2
```
Use latest version, instead of the constant

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +        env:
for "On-Prem" Github server, we also need to get and set the API ENDPOINT URL
It should be requested from the users and passed to: `JF_GIT_API_ENDPOINT` (same for scan PR)

2024-10-09 13:31 UTC, attiasas commented on src/services/FrogbotService.ts
> +          JFROG_CLI_LOG_LEVEL: "DEBUG"
should we include DEBUG for every run?

2024-10-09 13:41 UTC, attiasas reviewed
Also remove unrelated triggers

2024-10-09 13:41 UTC, attiasas commented on src/services/FrogbotService.ts
> +      - "${PULL_REQUEST_DATA.branchName}"
remove trigger

2024-10-09 13:41 UTC, attiasas commented on src/services/FrogbotService.ts
> +      - trigger-frogbot-scan
remove trigger

2024-10-11 21:22 UTC, eyalk007 commented on src/app.ts
> +  if (payload.action === "added") {
yes.

the other action is installation. in instalation we create a post request not webhook(in stage 2 of the poc)

regarding not adding if exists.
i will get error 421/422 (cant remember which one) from the api if exists.
i need information about the error handeling from the product to know what to do with the error .
but it wont install if Frogbot exists

2024-10-11 21:22 UTC, eyalk007 commented on src/services/FrogbotService.ts
> +        //TODO: add reviewers funcionality
product needs to decide who is added

2024-10-11 21:24 UTC, eyalk007 commented on src/services/FrogbotService.ts
> +        env:
on prem requires more configs in general and is not for the poc. 
will add a todo instead, as it is a case we will need to handle

2024-10-13 09:08 UTC, eyalk007 commented
tests will be added in the next stage

2024-10-13 14:18 UTC, attiasas commented on README.md
> +
You can extend it with general important information about the behind-the-scenes how the service works, its structure, and some debugging information if you can (required inputs/env vars to run...)
It will help us remember or for others to step in quickly.

2024-10-13 14:18 UTC, attiasas commented on src/app.ts
> +const secret: string = process.env.WEBHOOK_SECRET as string;
Add a comment about each const, what is `appId`? what is the needed key?... 
Since you are getting those values as inputs, It will help maintain and other debug in the future.

2024-10-13 14:18 UTC, attiasas commented on src/app.ts
> +      await Promise.all(installFrogbotPromises);
```suggestion
      await Promise.allSettled(installFrogbotPromises);
```
I think `all` will reject and finish if any rejected, we want to abstract one install from another right?
If think `allSettled` is the right one for this case but make sure

2024-10-13 14:18 UTC, attiasas commented on src/app.ts
> +const port: number = parseInt(process.env.PORT || '3000', 10);
please group all var inputs together/close. prefer at the top, it will help maintain this.

2024-10-13 14:18 UTC, attiasas commented on src/services/FrogbotService.ts
> +            await Promise.all([
make sure about `all` here as well

2024-10-13 14:18 UTC, attiasas commented on src/services/FrogbotService.ts
> +    private async openPullRequest(owner: string, repo: string, defaultBranch: string) {
I would extract all github only functions to its own static class `GitHubUtils` in different file for readability and order (createBranch, allowWorkflows..., maybe extract some specific logic to a general one with more args...)

2024-10-13 14:18 UTC, attiasas commented on src/services/FrogbotService.ts
> +    private scanRepositoryWorkflow(defaultBranch: string): string {
maybe move `pullRequestWorkflow` and `scanRepositoryWorkflow` to `consts.ts` or there own `template` files

2024-10-13 14:19 UTC, eyalk007 commented on README.md
> +
Thats going to change pretty drastically in the next pr
So i see no reason to expand in it now

2024-10-13 14:21 UTC, eyalk007 commented on src/services/FrogbotService.ts
> +    private scanRepositoryWorkflow(defaultBranch: string): string {
They are really more utils than consts as they are functions

2024-10-13 17:32 UTC, eyalk007 commented on src/app.ts
> +      await Promise.all(installFrogbotPromises);
i mean it changes in phase 2

2024-10-13 17:32 UTC, eyalk007 commented on src/services/FrogbotService.ts
> +            await Promise.all([
here if one fails i want to stop

2024-10-13 17:34 UTC, eyalk007 commented on src/services/FrogbotService.ts
> +    private async openPullRequest(owner: string, repo: string, defaultBranch: string) {
hard disagree. i am already using a client that makes it all for me (octokit is the official api client for github).
wrapping it is just making a wrapper for a wrapper.
I dont want to make air conditioners

2024-10-14 10:15 UTC, attiasas approved these changes

2024-10-14 10:21 UTC, merged